export const TEAM_SLUG_MAP: Record<string, string> = {
    静岡ブルーレヴズ: "shizuoka-blue-revs",
    東京サントリーサンゴリアス: "tokyo-suntory-sungoliath",
    "浦安D-Rocks": "urayasu-d-rocks",
    コベルコ神戸スティーラーズ: "kobelco-kobe-steelers",
    埼玉パナソニックワイルドナイツ: "saitama-panasonic-wild-knights",
    東芝ブレイブルーパス東京: "toshiba-brave-lupus-tokyo",
    トヨタヴェルブリッツ: "toyota-verblitz",
    三重ホンダヒート: "mie-honda-heat",
    三菱重工相模原ダイナボアーズ: "mitsubishi-sagamihara-dynaboars",
    横浜キヤノンイーグルス: "yokohama-canon-eagles",
    リコーブラックラムズ東京: "ricoh-black-rams-tokyo",
    NECグリーンロケッツ東葛: "nec-green-rockets-tokatsu",
    九州電力キューデンヴォルテクス: "kyuden-voltex",
    清水建設江東ブルーシャークス: "shimizu-koto-blue-sharks",
    豊田自動織機シャトルズ愛知: "toyota-shuttles-aichi",
    日本製鉄釜石シーウェイブス: "kamaishi-seawaves",
    花園近鉄ライナーズ: "hanazono-kintetsu-liners",
    日野レッドドルフィンズ: "hino-red-dolphins",
    レッドハリケーンズ大阪: "hurricanes",
    "Red Hurricanes Osaka": "hurricanes",
    "Red Hurricanes": "hurricanes",
    クリタウォーターガッシュ昭島: "kurita-water-gush-akishima",
    狭山セコムラガッツ: "secom-rugguts",
    中国電力レッドレグリオンズ: "chugoku-red-regulions",
    マツダスカイアクティブズ広島: "mazda-skyactivs-hiroshima",
    ヤクルトレビンズ戸田: "yakult-levins",
    "クボタスピアーズ船橋・東京ベイ": "kubota-spears-funabashi-tokyo-bay",
    ルリーロ福岡: "leriro-fukuoka",

    // Top 14
    "トゥールーズ": "toulouse",
    "Stade Toulousain": "toulouse",
    "ボルドー・ベグル": "bordeaux",
    "Union Bordeaux-Bègles": "bordeaux",
    "スタッド・フランセ": "paris",
    "Stade Français Paris": "paris",
    "Stade Français": "paris",
    "トゥーロン": "toulon",
    "RC Toulonnais": "toulon",
    "ラ・ロシェル": "la-rochelle",
    "Stade Rochelais": "la-rochelle",
    "ラシン92": "racing-92",
    "Racing 92": "racing-92",
    "リヨン": "lyon",
    "Lyon OU": "lyon",
    "カストル": "castres",
    "Castres Olympique": "castres",
    "ポー": "pau",
    "Section Paloise": "pau",
    "ペルピニャン": "perpignan",
    "USA Perpignan": "perpignan",
    "バイヨンヌ": "bayonne",
    "Aviron Bayonnais": "bayonne",
    "クレルモン": "clermont",
    "ASM Clermont Auvergne": "clermont",
    "モンペリエ": "montpellier",
    "Montpellier Hérault Rugby": "montpellier",
    "ヴァンヌ": "vannes",
    "RC Vannes": "vannes",

    // Super Rugby
    "Auckland Blues": "blues",
    "Blues": "blues",
    "Waikato Chiefs": "chiefs",
    "Chiefs": "chiefs",
    "Canterbury Crusaders": "crusaders",
    "Crusaders": "crusaders",
    "Otago Highlanders": "highlanders",
    "Highlanders": "highlanders",
    "Wellington Hurricanes": "hurricanes",
    "Hurricanes": "hurricanes",

    // URC
    "ドラゴンス": "dragons-rugby",
    "Dragons RFC": "dragons-rugby",
    "Dragons Rugby": "dragons-rugby",
    "アルスター": "ulster-rugby",
    "Ulster Rugby": "ulster-rugby",
    "グラスゴー・ウォリアーズ": "glasgow-warriors",
    "Glasgow Warriors": "glasgow-warriors",
    "Glasgow": "glasgow-warriors",
    "ヴォーダコム・ブルズ": "vodacom-bulls",
    "Vodacom Bulls": "vodacom-bulls",
    "レンスター・ラグビー": "leinster-rugby",
    "Leinster Rugby": "leinster-rugby",
    "マンスター・ラグビー": "munster-rugby",
    "Munster Rugby": "munster-rugby",
    "DHLストーマーズ": "dhl-stormers",
    "DHL Stormers": "dhl-stormers",
    "ハリウッドベッツ・シャークス": "hollywoodbets-sharks",
    "Hollywoodbets Sharks": "hollywoodbets-sharks",
    "エミレーツ・ライオンズ": "emirates-lions",
    "Emirates Lions": "emirates-lions",
    "Fidelity SecureDrive Lions": "emirates-lions",
    "Benetton Rugby": "benetton-rugby-trevise",
    "Benetton": "benetton-rugby-trevise",
    "ベネットン・ラグビー・トレヴィーゾ": "benetton-rugby-trevise",
    "Dragons": "dragons-rugby",
    "Ospreys": "ospreys",
    "オスプリーズ": "ospreys",
    "Connacht Rugby": "connacht-rugby",
    "コナート・ラグビー": "connacht-rugby",
    "Scarlets": "scarlets",
    "スカーレッツ": "scarlets",
    "Edinburgh Rugby": "edinburgh-rugby",
    "エディンバラ・ラグビー": "edinburgh-rugby",
    "Cardiff Rugby": "cardiff-rugby",
    "カーディフ・ラグビー": "cardiff-rugby",
    "Zebre Parma": "zebre-parma",
    "ゼブレ・パルマ": "zebre-parma",

    // Premiership
    "Northampton Saints": "northampton-saints",
    "ノーサンプトン・セインツ": "northampton-saints",
    "Bath Rugby": "bath-rugby",
    "バース・ラグビー": "bath-rugby",
    "Bristol Bears": "bristol-bears",
    "ブリストル・ベアーズ": "bristol-bears",
    "Leicester Tigers": "leicester-tigers",
    "レスター・タイガーズ": "leicester-tigers",
    "Exeter Chiefs": "exeter-chiefs",
    "エクセター・チーフス": "exeter-chiefs",
    "Saracens": "saracens",
    "サラセンズ": "saracens",
    "Sale Sharks": "sale-sharks",
    "セール・シャークス": "sale-sharks",
    "Gloucester Rugby": "gloucester-rugby",
    "グロスター・ラグビー": "gloucester-rugby",
    "Harlequins": "harlequins",
    "ハリクインズ": "harlequins",
    "Newcastle Falcons": "newcastle-falcons",
    "ニューカッスル・ファルコンズ": "newcastle-falcons"
};

/**
 * チーム名からスラッグを取得する
 * @param name チーム名
 * @returns スラッグ
 */
export function getTeamSlug(name: string): string {
    if (TEAM_SLUG_MAP[name]) {
        return TEAM_SLUG_MAP[name];
    }
    // 特殊文字の置換と小文字化
    return name
        .toLowerCase()
        .replace(/\s+/g, "-")
        .replace(/[・.&\/]/g, "-")
        .replace(/-+/g, "-")
        .replace(/^-|-$/g, "");
}
